# Generated by Django on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, default='MBBS, MD', max_length=120),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital_name',
            field=models.CharField(default='City Care Hospital, Lucknow', max_length=160),
        ),
    ]
