# Generated by Django 5.2.17 on 2026-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctorprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('checked_in', 'Checked-in'), ('waiting', 'Waiting'), ('calling', 'Calling'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='upcoming', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Receptionist', 'Receptionist')], default='Doctor', max_length=20),
        ),
    ]
