# Generated by Django 5.2.17 on 2026-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_appointment_clinical_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
