const hospitalDepartments = [
  'General Medicine',
  'Cardiology',
  'Neurology',
  'Pediatrics',
  'Orthopedics',
  'Dermatology',
  'Gynecology',
  'Ophthalmology',
  'ENT',
  'Dentistry',
  'Pulmonology',
  'Gastroenterology',
  'Psychiatry',
  'Oncology',
  'Emergency Medicine',
];
